In [1]:
#1. Import the numpy package under the name np (★☆☆)
import numpy as np

In [2]:
#2. Print the numpy version and the configuration (★☆☆)
print(np.__version__)
np.show_config()


2.2.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-_1vgc7re/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-_1vgc7re/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-_1vgc7re/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-_1vgc7re/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.

In [4]:
#3. Create a null vector of size 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
#4. How to find the memory size of any array
my_array=np.zeros((5,4))
print(f"{my_array.size*my_array.itemsize} bytes")

160 bytes
20 bytes
8 bytes


In [17]:
#5. How to get the documentation of the numpy add function from the command line?
np.info(np.add)
# In cmd: python -c "import numpy; numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [18]:
#6. Create a null vector of size 10 but the fifth value which is 1
my_array=np.zeros(10)
my_array[4]=1
print(my_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [20]:
#7. Create a vector with values ranging from 10 to 49
my_array=np.arange(10,50)
print(my_array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [24]:
#8. Reverse a vector (first element becomes last)
my_array=np.arange(30)
reverse=my_array[::-1]
print(reverse)

[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0]


In [27]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
my_array=np.arange(0,9).reshape(3,3)
print(my_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] 
my_array=np.array([1,2,0,0,4,0])
index=np.nonzero(my_array)
print(index)

(array([0, 1, 4]),)


In [37]:
#11. Create a 3x3 identity matrix
iden_matrix=np.eye(3,3)
print(iden_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
#12. Create a 3x3x3 array with random values
my_array=np.random.random((3,3,3))
my_array

array([[[0.18219713, 0.47667413, 0.63493722],
        [0.45508574, 0.57324608, 0.49668564],
        [0.46486344, 0.9576273 , 0.54069794]],

       [[0.86209086, 0.29382238, 0.34288264],
        [0.75591257, 0.42834007, 0.0717534 ],
        [0.16488454, 0.15714137, 0.83407446]],

       [[0.30934816, 0.62480892, 0.22921255],
        [0.85454004, 0.06592188, 0.52801021],
        [0.62903551, 0.10918157, 0.08403858]]])

In [44]:
#13. Create a 10x10 array with random values and find the minimum and maximum values 
my_array=np.random.random((10,10))
max=my_array.max()
min=my_array.min()
print(my_array)
print(max)
print(min)

[[0.80290201 0.54710177 0.49609637 0.59157626 0.38936019 0.17004867
  0.35584759 0.16453786 0.63113513 0.46528339]
 [0.67651771 0.27810648 0.11757779 0.45612076 0.6267077  0.9542766
  0.4054014  0.82325301 0.49270327 0.27533102]
 [0.81812513 0.28917643 0.7998204  0.64176223 0.56895707 0.99597744
  0.96177902 0.30861939 0.22990432 0.3086552 ]
 [0.399949   0.3320359  0.71035962 0.31709504 0.47144636 0.41199105
  0.75840703 0.44634802 0.67983446 0.29312359]
 [0.34683693 0.15671643 0.01573863 0.72277078 0.82806629 0.02047148
  0.64363788 0.21914085 0.52295531 0.6723896 ]
 [0.76734611 0.87533403 0.74133477 0.82873898 0.96435556 0.89461233
  0.12997345 0.5354543  0.86207213 0.15945344]
 [0.55280622 0.84369678 0.53948274 0.81877396 0.50700872 0.62984528
  0.78223044 0.38934652 0.45224321 0.15744901]
 [0.60102035 0.59413686 0.03432381 0.48930851 0.62748618 0.17513154
  0.08074925 0.32290574 0.97840461 0.70274761]
 [0.63478681 0.62411281 0.19912579 0.36875765 0.62581697 0.11557605
  0.74042994 

In [45]:
#14. Create a random vector of size 30 and find the mean value
my_array=np.random.random(30)
mean=my_array.mean()
print(mean)

0.5123334119770526


In [54]:
#15. Create a 2d array with 1 on the border and 0 inside
my_array=np.ones((8,10))
print(my_array)
#my_array[1:7,1:9]=0
my_array[1:-1,1:-1]=0
print(my_array)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [56]:
#16. How to add a border (filled with 0's) around an existing array?
my_array=np.random.random((3,5))
my_array=np.pad(my_array, pad_width=1, mode='constant', constant_values=0)
print(my_array)

[[0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.1847523  0.26430474 0.58069574 0.35199073 0.50258669
  0.        ]
 [0.         0.22616294 0.61724087 0.79233173 0.19447447 0.30910353
  0.        ]
 [0.         0.42227934 0.39354761 0.5499145  0.15084602 0.18932655
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]]


In [57]:
#17. What is the result of the following expression? 
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [61]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
my_matrix=np.diag(1+np.arange(4), k=-1)
my_matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [69]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
my_array=np.zeros((8,8), dtype=int)
my_array[1::2, ::2]=1
my_array[:1:2, 0::2]=1
my_array

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [70]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(100,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(4))


In [74]:
#21. Create a checkerboard 8x8 matrix using the tile function
my_array=np.array([[0,1],[1,0]])
my_matrix=np.tile(my_array,(4,4))
my_matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [78]:
#22. Normalize a 5x5 random matrix
my_matrix=np.random.random((5,5))
normal=(my_matrix-np.mean(my_matrix))/(np.std(my_matrix))
print(normal)
print(np.mean(normal))
print(np.std(normal))

[[-0.01717601  0.37804142  0.9657793   0.42471796  1.45168538]
 [ 0.62896914  0.25228754 -1.21897719 -1.36463836  1.42392628]
 [-1.31853463  1.10576111  0.09926821  0.48739883  1.38205922]
 [-0.47220746 -0.64069705  1.39409469 -1.04291064  0.12303719]
 [-0.77481892 -0.7597925  -1.63207737 -1.61626682  0.74107066]]
-4.4408920985006264e-17
1.0


In [79]:
#23.Create a custom dtype that describes a color as four unsigned bytes
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

In [91]:
#24.  Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
array1=np.random.random((5,3))
array2=np.random.random((3,2))

print(np.dot( array1,array2))
print(array1 @ array2)

[[0.9318462  1.03655735]
 [0.98768751 0.73289404]
 [0.45695034 0.9623926 ]
 [1.06749359 0.58205572]
 [0.27620534 0.30297898]]
[[0.9318462  1.03655735]
 [0.98768751 0.73289404]
 [0.45695034 0.9623926 ]
 [1.06749359 0.58205572]
 [0.27620534 0.30297898]]


In [95]:
#25.Given a 1D array, negate all elements which are between 3 and 8, in place.
my_array=np.array([3,5,15,13,0,-3])
# for index in range(len(my_array)):
#     if 3 < my_array[index] <= 8:
#         my_array[index] = -my_array[index]
my_array[(my_array > 3) & (my_array <= 8)] *= -1

print(my_array)

[ 3 -5 15 13  0 -3]


In [1]:
#26. What is the output of the following script? 
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [6]:
#27. Consider an integer vector Z, which of these expressions are legal?
import numpy as np
Z=np.arange(6)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [10]:
#28. What are the result of the following expressions? 
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\hp\AppData\Local\Temp\ipykernel_91284\3627246184.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\hp\AppData\Local\Temp\ipykernel_91284\3627246184.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\hp\AppData\Local\Temp\ipykernel_91284\3627246184.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


In [13]:
#29. How to round away from zero a float array ?
my_array = np.random.uniform(-5, 10, 8)
print(my_array)
print (np.copysign(np.ceil(np.abs(my_array)), my_array))

[-1.65353027  8.03653231 -1.90679298 -4.14385168 -0.33835656 -2.48832471
 -0.92827606  7.44753125]
[-2.  9. -2. -5. -1. -3. -1.  8.]


In [19]:
#30. How to find common values between two arrays? 
array1=np.random.randint(-5,10,8)
array2=np.random.randint(-8,10,6)
print(array1)
print(array2)
print(np.intersect1d(array1, array2))

[ 7  9  6  7 -2  7 -5  7]
[ 7 -3  4 -3 -5  8]
[-5  7]
